#!/bin/bash

DIR="$( cd "$( dirname $0 )" && pwd )"
FILE=$1
RSPEC_OPTIONS=

if [ $FILE ];
then
  rpsec "$FILE" --format documentation --color
else
  rspec "$DIR/../spec" --format documentation --color
fi
